### ISSUE TITLE
Cannot call a method on a null-value

### ISSUE THREAD

**Issue by christrotter** [matthewhatch/NCache#2]
Good morning!  Thanks so much for creating this module, I'm already finding it very helpful.  We are using 'free' NCache and so don't have any monitoring/auto-start capabilities, so decided that a self-healing monitoring script was a reasonable approach to take.

I can reproduce this by using the CLI 'stopcache' tool to stop our 'devtest' instance, then running our script.  If I run our script when the instance is running, no errors.

I would note that this 'error' doesn't seem to impact functionality.

``` powershell
PS C:\sci\NCache\bin\tools> .\ncache-instance-check.ps1 server1 devtest
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\ncache\ncache.psm1:300 char:21
+                     $properties = @{
+                     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Remove-Variable : Cannot find a variable with the name 'properties'.
At C:\Program Files\WindowsPowerShell\Modules\ncache\ncache.psm1:316 char:17
+                 Remove-Variable -Name properties
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (properties:String) [Remove-Variable], ItemNotFoundEx
    + FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.RemoveVariableCommand
```

Here's our script that uses your most excellent module:

``` powershell
param(
    [parameter(Mandatory=$true,Position=0)][string]$hostName,
    [parameter(Mandatory=$True,Position=1)][string]$instanceName
)

# Here we use the SCI moduleFunctions to safely add a custom module
Import-Module moduleFunctions
Add-CustomModule NCache

# Nagios return states
$returnStateOK       = 0
$returnStateWarning  = 1
$returnStateCritical = 2
$returnStateUnknown  = 3

function Check-CacheStatus {
    param(
        [parameter(position=0)][string]$ComputerName,
        [parameter(position=1)][string]$CacheId
    )

    [string]$instanceStatus = $(Get-CacheDetails -computername $ComputerName -cacheid $CacheId).Status

    # Write "OK" and exit the script if the instance is running
    if ($instanceStatus -eq "Running") {
       Write-Host "OK - $instanceName is running."
       exit $returnStateOK
    }
}

# Check instance status
Check-CacheStatus $hostName $instanceName

# Not running; attempt to restart
Write-Host "RUH ROH - $instanceName is stopped. Attempting to restart it..."
Restart-Cache -computername $hostName -cacheid $instanceName

# Check it again
Check-CacheStatus $hostName $instanceName

# Not running and restart didn't work; critical time
Write-Host "Oh noes - $instanceName is still not running."
exit $returnStateCritical 
```

I've run out of time...but hopefully that's a helpful start.

**Comment by matthewhatch** [comment]
Great to hear this is helping you.  I'll check this out tonight.

**Comment by matthewhatch** [comment]
My guess is this happens when the cache is not running, the code in Get-CacheDetails doesn't handle that scenario very well (really it's pretty sloppy)… I'll have time to update it over the weekend.

**Comment by christrotter** [comment]
Hehe, our script still works, but looks like this:
![image](https://cloud.githubusercontent.com/assets/8292406/8498020/2ce3de5e-2150-11e5-8dd0-b9ce2e01963e.png)

I think we need to re-do it to accept multiple cache instances in an array rather than running the script once per instance.  The check_mk_agent takes ~5s to run one instance check.

We are reasonably set on using NCache as a key piece of our infrastructure, so if you need help testing any of this we are at your service!

**Comment by matthewhatch** [comment]
I just created a new branch called Issue2 and checked in the fix.  Do you want to test with this branch before I merge it to master?

**Comment by christrotter** [comment]
Just tested that, no more error!  Nice work.

**Comment by matthewhatch** [comment]
Nice… just merged the fix to main
